### ISSUE TITLE
Consider adding a version check method

### ISSUE THREAD

**Issue by gRegorLove** [microformats/php-mf2#133]
We ran into an issue where it appears different (WordPress) plugins are packaged with php-mf2 and thus might use different versions. There doesn't appear to be an easy way to check the php-mf2 version, so perhaps we should add a version check method. I'm not sure what the best practices are for this, pros/cons, etc. Let's discuss.

https://chat.indieweb.org/dev/2017-06-17#t1497727068625000

**Comment by dshanske** [comment]
Can we milestone this for 0.50?

**Comment by Zegnat** [comment]
Interesting. I guess this is relatively WordPress specific? Or at least a problem specific to any system where dependencies are likely to pack their own dependencies 🤔 I do not think there are a lot of best practices for this, I at least have no seen them.

But what I would do is add a [class constant](https://www.php.net/manual/en/language.oop5.constants.php) to the `Parser` class, probably called `VERSION` to sort of go along with things like [`PHP_VERSION`](https://www.php.net/manual/en/reserved.constants.php) and [`OPENSSL_VERSION_TEXT`](https://www.php.net/manual/en/openssl.constversion.php) etc. (I would limit it to a class constant rather than global just for namespacing.)

Make it a string, just like those two examples, containing our version. E.g. `0.5.0`. By using a string value the native [`version_compare`](https://www.php.net/manual/en/function.version-compare.php) could be used. Code can then do something like:

```php
if (false === defined(Parser::class . "::VERSION")) {
    // Older than 0.5.0, no version available yet.
} else if (version_compare(Parser::VERSION, '0.6.0', '>=')) {
    // Using native version_compare of PHP to check whether parser version is at least 0.6.0.
}
```

**Comment by dshanske** [comment]
I think the constant is the right solution.

**Comment by pfefferle** [comment]
This might help to identify the version of the parser, but I think it does not help with the WordPress problem. I am not sure how to handle the includes of different plugins with the pseudo code above. The only valid way I identifies is, to change the namespace of the lib: https://github.com/pfefferle/wordpress-webmention/blob/master/config/php-scoper/mf2.inc.php

The constant might cause other issues, if we forget to update it, before a new version.

**Comment by Zegnat** [comment]
Hmm, if we do not think it will help Wordpress (or some other platform that php-mf2 is deployed in), I do wonder about the worth of this change.

I agree with @pfefferle that a constant like this is always a bit finicky because it can be missed at updates; it will probably be a manual field to be updated. It would be much better if we did not have to include overhead like that.

@dshanske did you have a specific use for this value in mind?

**Comment by dshanske** [comment]
Just as a check. But there are other ways to do it. For now, I'd say close as due no specific use case.

**Comment by Zegnat** [comment]
Closing then, of course feel free to reopen or file a new issue if a future use-case does come up!
